#!/bin/sh
# prepare-commit-msg hook

fixup_mode_pattern='^(squash|amend|fixup)\! +'
[[ $(<"$1") =~ $fixup_mode_pattern ]] && echo "fixup mode" && exit 0

branch_name="$(git branch --show-current)"
[ -z "$branch_name" ] && echo "rebase mode" && exit 0 || echo "branch: $branch_name"

cat "$1" | sed "s/^/original message: /"
cat "$1" | sed -E "1s|^(.+?:\s*)?|$branch_name: |" > $1
cat "$1" | sed "s/^/modified message: /"
[ -s $1 ] || exit 1